// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hilbertMapping
NumericVector hilbertMapping(NumericMatrix x, int bits);
RcppExport SEXP hilbertSimilarity_hilbertMapping(SEXP xSEXP, SEXP bitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type bits(bitsSEXP);
    __result = Rcpp::wrap(hilbertMapping(x, bits));
    return __result;
END_RCPP
}
