// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hilbertMapping
NumericVector hilbertMapping(NumericMatrix x, int bits);
RcppExport SEXP hilbertSimilarity_hilbertMapping(SEXP xSEXP, SEXP bitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type bits(bitsSEXP);
    rcpp_result_gen = Rcpp::wrap(hilbertMapping(x, bits));
    return rcpp_result_gen;
END_RCPP
}
